[versions]
minecraft = "26.1.2"
mc-range = "~26.1"
fabric-api = "0.155.2+26.1.2"
moulconfig = "4.7.2"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
moulconfig = { module = "org.notenoughupdates.moulconfig:modern-26.1", version.ref = "moulconfig" }
